development:
  adapter: postgresql
  database: bluecheckpoint_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

test:
  adapter: postgresql
  database: bluecheckpoint_test
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  database: bluecheckpoint_production
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: localhost
